# GENERATE TIME: Wed Nov  9 13:24:52 2022
# CMD:
# basicsr/train.py -opt options/train/train_HorSR_x2.yml

# general settings
name: H04_HorSR_L1_1000k_P474K_x2
model_type: SRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
#    dataroot_gt: D:/ImageSuper-ResolutionData/DF2K/DF2K_train_HR
#    dataroot_lq: D:/ImageSuper-ResolutionData/DF2K/DF2K_train_LR_bicubic/X4
#    (for lmdb)
    dataroot_gt: D:/ImageSuper-Resolution/BSRN-main/datasets/DF2K/DF2K_train_HR_sub.lmdb
    dataroot_lq: D:/ImageSuper-Resolution/BSRN-main/datasets/DF2K/DF2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb
      # (for lmdb)
      # type: lmdb

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 100
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Set5/HR
    dataroot_lq: datasets/benchmark/Set5/LR_bicubic/X2
    io_backend:
      type: disk

# network structures
network_g:
  type: HorSR
  depths: [1, 2, 3, 2]
  base_dim: 64
  upscale: 2


# path
path:
  pretrain_network_g: ~
  param_key_g:   params_ema
  strict_load_g: ture
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000, 250000, 250000, 250000]
    restart_weights: [1, 1, 1, 1]
    eta_min: !!float 1e-7


  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: H07_HorSR_L1_1000k_P476K_X3
    resume_id:
    entity: chu625987740

# dist training settings
dist_params:
  backend: nccl
  port: 29500
